version: '3'

services:
  jekyll:
    container_name: training-material
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - .:/site
    ports:
      - '8080:8080'

